[package]
name = "marklip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clipboard-rs = "0.3.1"
htmd = "0.5.0"
markdown = "1.0.0"
notify-rust = { version = "4.11.7", default-features = false }
thiserror = "1.0"
strip_markdown = "0.2.0"
